---
driver:
  name: vagrant

platforms:
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-8.7
- name: centos-6.8
- name: centos-7.3

suites:
- name: default
  run_list: ["recipe[bind]"]
  attributes:
    bind:
      masters: [ "127.0.0.1" ]
      zones:
        attribute: [ "example.com" ]
      options: [ "check-names slave ignore;", "multi-master yes;", "provide-ixfr yes;", "request-ixfr yes;" ]
      server:
        127.0.0.1:
        - 'bogus no;'
